export const buttonPresetColors = {
    blue: {
        outlined: [
            'text-blue-700',
            'border',
            'border-blue-700',
            'hover:bg-blue-700',
            'hover:text-white',
            'focus:ring-4',
            'focus:outline-none',
            'focus:ring-blue-300',
            'font-medium',
            'text-sm',
            'p-2.5',
            'text-center',
            'inline-flex',
            'items-center',
            'me-2', // icnon left or right
            'dark:border-blue-500',
            'dark:text-blue-500',
            'dark:hover:text-white',
            'dark:focus:ring-blue-800',
            'dark:hover:bg-blue-500',
        ],
        noOutlined: [
            'text-white',
            'bg-blue-700',
            'hover:bg-blue-800',
            'focus:ring-4',
            'focus:outline-none',
            'focus:ring-blue-300',
            'font-medium',
            'text-sm',
            'px-5',
            'py-2.5',
            'text-center',
            'inline-flex',
            'items-center',
            'me-2', // icnon left or right
            'dark:bg-blue-600',
            'dark:hover:bg-blue-700',
            'dark:focus:ring-blue-800',
        ],
        shared: {},
    },
};
