const genButtonPresetColors = () => {
    let _presetColors = {
        primary: {
            outlined: [
                'border',
                'border-primary',
                'hover:bg-primary',
                'hover:text-white',
                'hover:bg-opacity-90',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-primary-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-primary',
                'dark:text-white',
                'dark:hover:text-white',
                'dark:focus:ring-primary-800',
                'dark:hover:bg-primary-500',
                'dark:hover:bg-opacity-80',
            ],
            noOutlined: [
                'text-white',
                'bg-primary',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-gray-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-primary',
                'hover:bg-opacity-90',
                'dark:focus:ring-gray-800',
            ],
            shared: {},
        },
        gray: {
            outlined: [
                'text-gray-700',
                'border',
                'border-gray-700',
                'hover:bg-gray-700',
                'hover:text-white',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-gray-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-gray-500',
                'dark:text-gray-400',
                'dark:hover:text-white',
                'dark:focus:ring-gray-800',
                'dark:hover:bg-gray-500',
            ],
            noOutlined: [
                'text-white',
                'bg-gray-700',
                'hover:bg-gray-800',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-gray-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-gray-600',
                'dark:hover:bg-gray-700',
                'dark:focus:ring-gray-800',
            ],
            shared: {},
        },
        'light-gray': {
            outlined: [
                'text-gray-400',
                'text-gray-900',
                'border',
                'border-gray-400',
                'hover:bg-gray-400',
                'hover:text-gray-200',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-gray-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-gray-600',
                'dark:text-gray-200',
                'dark:hover:bg-gray-200',
                'dark:hover:text-gray-700',
                'dark:focus:ring-gray-800',
            ],
            noOutlined: [
                'text-gray-700',
                'bg-gray-200',
                'hover:opacity-80',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-gray-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-gray-200',
                'dark:hover:bg-gray-200',
                'dark:focus:ring-gray-800',
            ],
            shared: {},
        },
        white: {
            outlined: [
                'text-gray-900',
                'border',
                'border-gray-800',
                'hover:text-gray-900',
                'hover:bg-gray-100',
                'focus:ring-4',
                'focus:outline-none',
                'focus:ring-gray-300',
                'font-medium',
                'rounded-lg',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                'me-2',
                'mb-2',
                'dark:border-gray-500',
                'dark:text-gray-200',
                'dark:hover:text-gray-900',
                'dark:hover:border-gray-200',
                'dark:hover:bg-gray-200',
                'dark:focus:ring-gray-800',
            ],
            noOutlined: [
                'text-gray-700',
                'bg-gray-50',
                'hover:opacity-90',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-gray-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-gray-50',
                'dark:hover:bg-gray-50',
                'dark:focus:ring-gray-800',
            ],
            shared: {},
        },
        'black-white': {
            outlined: [
                'text-gray-900',
                'hover:text-white',
                'border',
                'border-gray-800',
                'hover:bg-gray-900',
                'focus:ring-4',
                'focus:outline-none',
                'focus:ring-gray-300',
                'font-medium',
                'rounded-lg',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                'me-2',
                'mb-2',
                'dark:border-gray-500',
                'dark:text-gray-200',
                'dark:hover:text-gray-700',
                'dark:hover:border-gray-200',
                'dark:hover:bg-gray-200',
                'dark:focus:ring-gray-800',
            ],
            noOutlined: [
                'text-gray-700',
                'bg-gray-50',
                'hover:opacity-90',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-gray-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-gray-50',
                'dark:hover:bg-gray-50',
                'dark:focus:ring-gray-800',
            ],
            shared: {},
        },
        red: {
            outlined: [
                'text-red-700',
                'border',
                'border-red-700',
                'hover:bg-red-700',
                'hover:text-white',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-red-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-red-500',
                'dark:text-red-500',
                'dark:hover:text-white',
                'dark:focus:ring-red-800',
                'dark:hover:bg-red-500',
            ],
            noOutlined: [
                'text-white',
                'bg-red-700',
                'hover:bg-red-800',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-red-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-red-600',
                'dark:hover:bg-red-700',
                'dark:focus:ring-red-800',
            ],
            shared: {},
        },
        'light-red': {
            outlined: [
                'text-red-400',
                'border',
                'border-red-400',
                'hover:bg-red-400',
                'hover:text-red-200',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-red-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-red-200',
                'dark:text-red-200',
                'dark:hover:bg-red-200',
                'dark:hover:text-red-700',
                'dark:focus:ring-red-800',
            ],
            noOutlined: [
                'text-red-700',
                'bg-red-200',
                'hover:opacity-80',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-red-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-red-200',
                'dark:hover:bg-red-200',
                'dark:focus:ring-red-800',
            ],
            shared: {},
        },
        blue: {
            outlined: [
                'text-blue-700',
                'border',
                'border-blue-700',
                'hover:bg-blue-700',
                'hover:text-white',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-blue-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-blue-500',
                'dark:text-blue-500',
                'dark:hover:text-white',
                'dark:focus:ring-blue-800',
                'dark:hover:bg-blue-500',
            ],
            noOutlined: [
                'text-white',
                'bg-blue-700',
                'hover:bg-blue-800',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-blue-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-blue-600',
                'dark:hover:bg-blue-700',
                'dark:focus:ring-blue-800',
            ],
            shared: {},
        },
        'light-blue': {
            outlined: [
                'text-blue-400',
                'border',
                'border-blue-400',
                'hover:bg-blue-400',
                'hover:text-blue-200',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-blue-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-blue-200',
                'dark:text-blue-200',
                'dark:hover:bg-blue-200',
                'dark:hover:text-blue-700',
                'dark:focus:ring-blue-800',
            ],
            noOutlined: [
                'text-blue-700',
                'bg-blue-200',
                'hover:opacity-80',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-blue-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-blue-200',
                'dark:hover:bg-blue-200',
                'dark:focus:ring-blue-800',
            ],
            shared: {},
        },
        green: {
            outlined: [
                'text-green-700',
                'border',
                'border-green-700',
                'hover:bg-green-700',
                'hover:text-white',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-green-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-green-500',
                'dark:text-green-500',
                'dark:hover:text-white',
                'dark:focus:ring-green-800',
                'dark:hover:bg-green-500',
            ],
            noOutlined: [
                'text-white',
                'bg-green-700',
                'hover:bg-green-800',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-green-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-green-600',
                'dark:hover:bg-green-700',
                'dark:focus:ring-green-800',
            ],
            shared: {},
        },
        yellow: {
            outlined: [
                'text-yellow-500',
                'border',
                'border-yellow-500',
                'hover:bg-yellow-500',
                'hover:text-white',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-yellow-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-yellow-500',
                'dark:text-yellow-500',
                'dark:hover:text-white',
                'dark:focus:ring-yellow-800',
                'dark:hover:bg-yellow-500',
            ],
            noOutlined: [
                'text-white',
                'bg-yellow-500',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-yellow-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-yellow-500',
                'dark:opacity-100',
                'dark:hover:opacity-90',
                'dark:hover:bg-yellow-500',
                'dark:focus:ring-yellow-800',
            ],
            shared: {},
        },
        orange: {
            outlined: [
                'text-orange-500',
                'border',
                'border-orange-500',
                'hover:bg-orange-500',
                'hover:text-white',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-orange-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-orange-500',
                'dark:text-orange-500',
                'dark:hover:text-white',
                'dark:focus:ring-orange-800',
                'dark:hover:bg-orange-500',
            ],
            noOutlined: [
                'text-white',
                'bg-orange-500',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-orange-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-orange-500',
                'dark:opacity-100',
                'dark:hover:opacity-90',
                'dark:hover:bg-orange-500',
                'dark:focus:ring-orange-800',
            ],
            shared: {},
        },
        'light-green': {
            outlined: [
                'text-green-400',
                'border',
                'border-green-400',
                'hover:bg-green-400',
                'hover:text-green-200',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-green-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-green-200',
                'dark:text-green-200',
                'dark:hover:bg-green-200',
                'dark:hover:text-green-700',
                'dark:focus:ring-green-800',
            ],
            noOutlined: [
                'text-blue-700',
                'bg-blue-200',
                'hover:opacity-80',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-blue-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-blue-200',
                'dark:hover:bg-blue-200',
                'dark:focus:ring-blue-800',
            ],
            shared: {},
        },
        green2: {
            outlined: [
                'text-green-700',
                'border',
                'border-green-700',
                'hover:bg-green-700',
                'hover:text-white',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-green-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-green-500',
                'dark:text-green-500',
                'dark:hover:text-white',
                'dark:focus:ring-green-800',
                'dark:hover:bg-green-500',
            ],
            noOutlined: [
                'text-white',
                'bg-green-700',
                'hover:bg-green-800',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-green-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-green-600',
                'dark:hover:bg-green-700',
                'dark:focus:ring-green-800',
            ],
            shared: {},
        },
        blue2: {
            outlined: [
                'text-blue-700',
                'border',
                'border-blue-700',
                'hover:bg-blue-700',
                'hover:text-white',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-blue-300',
                'font-medium',
                'text-sm',
                'p-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:border-blue-500',
                'dark:text-blue-500',
                'dark:hover:text-white',
                'dark:focus:ring-blue-800',
                'dark:hover:bg-blue-500',
            ],
            noOutlined: [
                'text-white',
                'bg-blue-700',
                'hover:bg-blue-800',
                'focus:ring-0',
                'focus:outline-none',
                'focus:ring-blue-300',
                'font-medium',
                'text-sm',
                'px-5',
                'py-2.5',
                'text-center',
                // 'inline-flex',
                'rounded-lg', 'text-sm', 'px-5', 'py-2.5', 'text-center', 'me-2', 'mb-2',
                'items-center',
                'dark:bg-blue-600',
                'dark:hover:bg-blue-700',
                'dark:focus:ring-blue-800',
            ],
            shared: {},
        },
    };

    _presetColors['success'] = _presetColors['green'];
    _presetColors['danger'] = _presetColors['red'];
    _presetColors['info'] = _presetColors['light-blue'];

    return _presetColors;
}

export const buttonPresetColors = genButtonPresetColors();
